version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: autofix-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - autofix-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3
  nginx-frontend:
    image: nginx
    container_name: autofix-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - autofix-frontend-network
    depends_on:      
      - react1
      - react2
      - react3
  postgres:
    container_name: autofix-postgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - autofix-postgres-volume:/var/lib/postgresql/data
    networks:
      - autofix-backend-network
    environment:      
      POSTGRES_PASSWORD: 1234
    ports:
      - 5435:5432 
  spring1:
    container_name: autofix-backend-container-1
    image: bcaices/spring-image
    ports:
      - 8091:8090
    environment:
      DB_HOST: autofix-postgres-container
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 1234
    networks:
      - autofix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring2:
    container_name: autofix-backend-container-2
    image: bcaices/spring-image
    ports:
      - 8092:8090
    environment:
      DB_HOST: autofix-postgres-container
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 1234
    networks:
      - autofix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring3:
    container_name: autofix-backend-container-3
    image: bcaices/spring-image
    ports:
      - 8093:8090
    environment:
      DB_HOST: autofix-postgres-container
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 1234
    networks:
      - autofix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  react1:
    container_name: autofix-frontend-container-1
    image: bcaices/react-image
    ports:
      - 3001:3000
    networks:
      - autofix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: autofix-frontend-container-2
    image: bcaices/react-image
    ports:
      - 3002:3000
    networks:
      - autofix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: autofix-frontend-container-3
    image: bcaices/react-image
    ports:
      - 3003:3000
    networks:
      - autofix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  autofix-postgres-volume:
networks:
  autofix-backend-network:
  autofix-frontend-network:
    